### ISSUE TITLE
Adding/Removing an element from a dictionary/enumerable in the Properties Window every second time causes the property to collapse.

### ISSUE THREAD

**Issue by dch-GH** [FlaxEngine/FlaxEngine#1911] opened 2023-11-10 07:31 UTC
**Issue description:**
What it says in the title. Here's a clip:
![UMuU43r](https://github.com/FlaxEngine/FlaxEngine/assets/66768086/374a66a9-cb15-4618-93a7-9f710753490b)

It triggers a collapse *every other* or every % 2  addition/removal.

**Flax version:**
master branch @ 22c8ec53426543c1d8192c2bf5744c0bb37b384c

**Comment by MineBill** [comment] 2023-11-10 08:48
This is caused by 74bcf7d9e598be82635086570555b41cd85b9988. Don't have time to debug it but removing these lines fixes this.

**Comment by mafiesto4** [comment] 2023-11-11 17:01
Fixed in ddaa5f9161fceb4c1120a49fa434e8668605c919..

**Closed by mafiesto4** 2023-11-11 17:01 UTC
Labels: bug, editor
