### ISSUE TITLE
[Bug] Actor Asset Property Fields get cleared on Script Compilation

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2481] opened 2024-04-23 17:48 UTC
**Issue description:**
If you have an actor selected, when script compilation finishes, then asset references will get cleared. It only happens to the selected actor. And if you deselect the actor before script compilation finishes, your good.

**Steps to reproduce:**
1. Create an actor with an asset referecne, like animated model or particle effect.
2. Link an asset, like a model and animation graph in animated model. Or a particle system in a particle effect or etc.
3. Select the actor, so the properties panel show the actor properties
4. Create a script. Doesn't matter what it does. Make a change, so you can save it.
5. Tab back to flax, let it compile. The actor should still be selected
6. When the engine finishes compiling, the asset properties of the actor are empty.

**Minimal reproduction project:**
Basic

**Flax version:**
1.8.6510

**Comment by Tryibion** [comment] 2024-09-11 12:44
Do you have an editor plugin that adds a proxy to the content database? (this could be either in your code, or the code of another plugin project) I have seen this issue occur when the content database is not immediately rebuilt after the proxies are added. Something like `Editor.ContentDatabase.Rebuild(true)` at the end of the editor plugin initialization tends to fix that issue.

**Comment by Myterian** [comment] 2024-09-11 16:52
Yes, I do and your suggestion seems to have done the trick (at least I can see it after quick testing only). I followed this tutorial. Maybe it needs a mention of this issue and how to fix it?
https://docs.flaxengine.com/manual/scripting/tutorials/custom-asset.html?tabs=code-csharp

**Comment by mafiesto4** [comment] 2024-11-26 15:27
This seems to be fixed in Flax 1.9 as I'm no longer able to reproduce it. I think there was an issue with marking object as modified by asset/object reference property.

**Comment by Myterian** [comment] 2024-11-27 01:25
yep, looks good

**Closed** 2024-12-06 13:52 UTC
Labels: bug, editor
