### ISSUE TITLE
Linux : "Cannot open selected project file because it does nost exists" (if path contains UTF-8 chars)

### ISSUE THREAD

**Issue by SuperUserNameMan** [FlaxEngine/FlaxEngine#2187] opened 2024-01-19 10:26 UTC
**Issue description:**
I'm on Linux Mint 21.2.

`FlaxEditor` displays messagebox `Cannot open selected project file because it does not exists` and terminate itself without more details.

**Steps to reproduce:**
- download https://vps2.flaxengine.com/store/builds/Package_1_07_06407/FlaxEditorLinux.zip ;
- unzip ;
- execute any `FlaxEditor` executable ;
- use the file selection dialog to open any `.flaxproj`

**Minimal reproduction project:**
- the default `Flax.flaxproj` provided with the `FlaxEditorLinux.zip` ;
- any project from `git clone https://github.com/FlaxEngine/FlaxSamples.git`.

**Flax version:**
https://vps2.flaxengine.com/store/builds/Package_1_07_06407/FlaxEditorLinux.zip

**Comment by MineBill** [comment] 2024-01-19 11:14
Unable to reproduce. Run the Flax editor with `-std`. Where is the editor and the samples located? What filesystem do you use? Your other issue seems filesystem-related as well and it seems weird.

**Comment by SuperUserNameMan** [comment] 2024-01-19 16:13
I've just found the problem.

It occurs when the path contains utf-8 characters.

I was testing into the `Download/` directory, which, in french, is named `Télécharger/`.

If I move the Flax tree into `Documents/`, it works.

(my filesystem is default Ext4)

**Comment by Tesla-J** [comment] 2024-02-11 10:50
> I've just found the problem.
> 
> It occurs when the path contains utf-8 characters.
> 
> I was testing into the `Downloads/` directory, which, in french, is named `Téléchargements/`.
> 
> If I move the Flax tree into `Documents/`, it works.
> 
> (my filesystem is default Ext4)

Thank you, now I can use the editor.

**Comment by mafiesto4** [comment] 2024-03-04 16:22
Fixed in 5fdf1789cefa5ee4b04fc63819eeb0df4602a545.

**Closed by mafiesto4** 2024-03-04 16:22 UTC
Labels: bug, platform
