### ISSUE TITLE
Dictionary editing is broken af

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#483] opened 2021-04-26 23:54 UTC
There's basically nothing working correctly with Dictionary editor. Stuff is not being updated. Stuff is being deleted, EditorDrawer is erroring, Editor is crashing..... All in all its better to edit Dictionary in notepad.

**Comment by stefnotch** [comment] 2021-04-27 05:48
Might be related to/a duplicate of https://github.com/FlaxEngine/FlaxEngine/issues/52

**Comment by honzapatCZ** [comment] 2021-04-27 06:51
Thats also one of its problems but its not all, it happens even if its the root Member

**Comment by mafiesto4** [comment] 2021-06-09 11:30
Does #542 helped with this issue?

**Comment by herocrab** [comment] 2021-06-19 02:38
I hit this problem today and I think "broken af" is a good description. You can't remove anything from dictionaries after you've added items to them in the editor. Wherever the dictionary data is being written, it's not cleaned up when deleting entries. I even made the Dictionary private, cooked my game, deleted the cache, binaries, closed the editor, re-opened the editor, made my dictionary public again and lol... all the old entries still came back. #542 does not help with the issue. All I have is a Prefab with a dictionary of <string, Actor>. It is the root member.

**Comment by herocrab** [comment] 2021-06-19 02:42
Ah I see, editing the prefab .json asset works as a workaround.

**Comment by mafiesto4** [comment] 2021-06-27 10:14
So I guess it's related to prefab serialization of dictionaries.

**Comment by mafiesto4** [comment] 2021-07-14 09:41
There was an issue with deserialization of dictionaries on prefab instances that didn't clear them before applying instance modification data. Fixed in https://github.com/FlaxEngine/Newtonsoft.Json/commit/ff6caf376876db66981b75abf22b17a4dd929135 and already updated `Newtonsoft.Json` on master.

**Comment by Menotdan** [comment] 2023-11-10 15:06
@mafiesto4 Is there a reason this was left open?

**Comment by mafiesto4** [comment] 2023-11-10 15:14
There were different issues with dictionaries over the past couple of years. Let's verify the current state before `1.8` and close this issue if the editing experience is fine now.

**Comment by mafiesto4** [comment] 2024-02-17 08:04
It looks like dictionaries editing works far better than it used to. Editor supports almost any key type (not only int, float, string but also enums and structures). Closing as done. Any new issues can be reported separately.

**Closed by mafiesto4** 2024-02-17 08:04 UTC
Labels: bug, editor
