### ISSUE TITLE
Prefab is somehow broken

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#533] opened 2021-05-25 23:19 UTC
I have a box collider in my Prefab that I can't access the settings of or destroy. This issue occurred after reimporting the model. Not sure if it is related or not.
Here is a video of me attempting this:

https://user-images.githubusercontent.com/35228400/119580243-5da1db80-be03-11eb-83b9-9306df9abb28.mp4

Here is the Prefab:
[Building_A.zip](https://github.com/FlaxEngine/FlaxEngine/files/6542884/Building_A.zip)

Error Log:
[ErrorLog.txt](https://github.com/FlaxEngine/FlaxEngine/files/6542900/ErrorLog.txt)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment] 2021-05-28 09:50
I have this option enabled on that prefab:
![image](https://user-images.githubusercontent.com/3464853/119965092-2f123500-bfaa-11eb-8a12-e20c7bd18401.png)

Log file doesn't specify more so it's quite hard to tell what's going on there.

But I was able to reproduce it in this way:
1) Create prefab with collider as a root (or other object)
2) Add child object
3) Set child object as a root
4) Try to delete that collider - notice delete option is disabled.

**Comment by mafiesto4** [comment] 2021-05-28 10:05
Nope, it's because if root is selected and user right-click on other node it uses that root for options showing. UI bug.

**Comment by mafiesto4** [comment] 2021-05-28 10:11
Fixed in 94ee82b58df03f098febb2fe040a435f6c7ecc8a.

**Closed by mafiesto4** 2021-05-28 10:11 UTC
Labels: bug, editor
