### ISSUE TITLE
Annoying Popups

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#540] opened 2021-06-01 03:28 UTC
This happens a lot.
Basically, these popup hints appear when I'm about to select something. As they appear they instantly block the mouse click basically nullifying my selection. I need to make sure when I want to click and option that no popup hint popups in the way before I attempt to select it.
![image](https://user-images.githubusercontent.com/35228400/120262478-18871900-c2dd-11eb-98eb-a257504a76cf.png)

**Flax version:**
Master Branch

**Comment by LCRW** [comment] 2021-06-01 04:55
While the tooltip could be considered a nice feature, especially when you have duplicate names in different folders, placement is annoying since it moves tooltip up like shown on items near the bottom of the list. hovering items at top positions tooltip nicely below the item.
At the very least needs to be put above the highlighted element rather than over it.

**Comment by Evildea** [comment] 2021-06-01 07:14
@LCRW Yeap, I agree. It's nice but is currently constantly getting in the way.

**Comment by mafiesto4** [comment] 2021-06-01 10:08
Likely caused by https://github.com/FlaxEngine/FlaxEngine/pull/470

**Comment by mafiesto4** [comment] 2021-06-01 10:44
Fixed in c5405183c9aaa1d84a6b62733100058c578394f4. Now only monitor bounds will be constraining the tooltip.

**Closed by mafiesto4** 2021-06-01 10:44 UTC
Labels: bug, confirmed, editor
