### ISSUE TITLE
Project won't open with Custom Material in Graphics Settings

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1993] opened 2023-11-26 01:37 UTC
**Issue description:**
Having a custom Post Processing Material in Graphics settings produces an error when trying to open a project. Opening process gets canceled
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/7e9d08d1-5f9e-4064-ac5f-7634b1f32c2a)

**Steps to reproduce:**
1. Create Post Fx Material
2. Assign to Graphics Settings and save everything
3. Close and try reopen proejct

**Minimal reproduction project:**
Blank

**Flax version:**
1.7.6406.1

**Comment by Menotdan** [comment] 2023-11-26 04:30
Can't reproduce this following the steps, using 1.7.1 from the launcher.

**Comment by Menotdan** [comment] 2023-11-27 04:33
Huh, after opening the same project much later without changing anything, I do actually get the same error. I think it may require restarting the launcher or something like that.

**Comment by mafiesto4** [comment] 2024-02-21 22:26
Fixed in d7dbc0fbdc70b49cbc9775699b340f22005732b5.

**Closed by mafiesto4** 2024-02-21 22:26 UTC
Labels: crash, editor, graphics
