### ISSUE TITLE
Material Editor: Parameters Missing in Editor

### ISSUE THREAD

**Issue by XeroWolf** [FlaxEngine/FlaxEngine#1763] opened 2023-10-21 23:40 UTC
Material Parameters don't show up in the material instance editor.
I've created a brand new project just to make sure mine wasn't messed up some how.
**Flax version**
 1.7.6401

![Screenshot 2023-10-21 185735](https://github.com/FlaxEngine/FlaxEngine/assets/2533461/4763a419-6c2c-44db-a2fd-82aa26ab240d)

It shows up as expected in 1.6
![good version](https://github.com/FlaxEngine/FlaxEngine/assets/2533461/af5694ae-81b6-48b9-b11f-31a6a3478f12)

**Comment by Chikinsupu** [comment] 2023-10-22 09:39
I just tried to replicate this bug, but everything works for me. Though i am on 1.7.6402.
Could you update the editor and check again, maybe it has been fixed?

And if the bug still occurs maybe check the Output Log or Log file itself for any errors

**Comment by mafiesto4** [comment] 2023-10-22 18:37
Regression from 8d9f4d72f563ebfc406aa81477c00b094754dcd2 fixed in 8b096a9286cc8e9585cbd751a1a85234fdc7cfcb

**Closed by mafiesto4** 2023-10-22 18:37 UTC
Labels: bug, editor
