### ISSUE TITLE
Terrain made from heightmap appears blocky

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2375] opened 2024-03-29 11:01 UTC
**Issue description:**
Making a terrain, trying to use a HDR, but it comes out stair stepped.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/439bc53a-d660-4935-b287-5bfcd0a86ab1)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/f6206799-8b13-4467-aedc-7d4a818c4b82)

**Steps to reproduce:**
Import Texture Set to , make a terrain then apply it. set the chunksize to 254, scale to 0.1,0.1,0.1 and 50000 heightmap scale to show the issue clearly. 

Texture is included in zip

**Minimal reproduction project:**

[Ridge_Bulge_Desert.zip](https://github.com/FlaxEngine/FlaxEngine/files/14803068/Ridge_Bulge_Desert.zip)

**Flax version:**
Master

**Comment by mafiesto4** [comment] 2024-03-29 12:19
Height value is stored in `RG` components and uses 16-bits. Value is normalized to `0-1` (as `(height - PatchOffset) / PatchHeight`) and quantized to range `0-65535`. Whens ampled in Vertex shader we revert that operation top get actual height. This allows us to store heights in more optimized 32-bit texture. Additional `BA` channels are used to store competed normal vector (there i also a special case of value marked a a hole).

In future, we could add support for using larger amount of bits for heightmap texture so it will have better representation for such terrain (at cost of performance).

For now, you can try increasing amount of patches used to represent that terrain and scale it manually in Editor.

**Comment by Muzz** [comment] 2024-04-01 03:52
Hmm, perhaps I'm doing something wrong. I'm not sure why it's stair stepping like that if that's the case, as it's clearly more blocky than 16 bit would imply. Wouldn't increasing patches just change the x and y resolution of the mesh, not remove vertical stair stepping?

**Comment by cNori** [comment] 2024-04-01 13:21
![image](https://github.com/FlaxEngine/FlaxEngine/assets/162097313/59de852b-7c31-4334-8cff-f134e5db38e6)
what is wrong with the format 

it is R11 G11 B10

for Heightmaps
u need RGB16 or RGB32.
there is not enough data in the texture.
source texture has steps if u used some program regenerate the texture in RGB16 or RGB32

**Comment by mafiesto4** [comment] 2024-04-02 10:40
@Muzz Could you upload that sample hdr heightmap here for testing/debugging purposes? Can be lower resolution of you don't want to share the whole file. It will make it easier to fix this problem.

**Comment by Muzz** [comment] 2024-04-02 14:35
It's in the zip file in the original post.

**Comment by mafiesto4** [comment] 2024-04-14 22:23
It might be a precision issue for the input data, as heightmap scale 50k is kind of close to 16bit unit limit. Here is an example of input heightmap format:
(left: R16G16BA16, right: R11G11B10)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/a02a9cf4-c7a7-4e5d-8289-a84f25c13d54)

I'll try to find solution for this.

**Comment by Muzz** [comment] 2024-04-15 02:51
Great thank you!

**Comment by mafiesto4** [comment] 2024-04-15 10:15
I locally changed texture formats for rgba32 (32-bit per-channel) and it's still blocky. Then I tested flat, tessellated terrain with manually applied heightmap and it still looks blocky:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/863b8051-bf0c-4e8a-b0cf-5b113ba804ad)

(left manual heightmap, right current engine state)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/d849260a-f1e3-4409-936d-d9d34b1ae31a)

I think the problem is with the source heightmap texture, even tho it's hdr and we load it's data as `float`s it's still too blocky as input to smoothly represent values from range `0-50000` (as used in this settings example).

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/9a65ef3c-b9d1-45bf-8d4f-1fa0bef6f89c)

@Muzz Have you tried this in other game engines?

**Comment by Muzz** [comment] 2024-04-16 04:22
I just checked in blender and it's banded.  My bad. 

I generated it out of JangaFX with their new program geogen and blindly assumed they programmed the export correctly. 

Who would have thought they would mess up the HDR heightmap export for a heightmap generation program...

**Comment by Muzz** [comment] 2024-04-16 04:39
Ok this is odd, i loaded a working exr into affinity photo and converted it to hdr and it got banded. I also tried an online converter and got the same result. 

Here is a working exr, but flax doesn't support the format. You can convert it and have a play though. 
[Ridge_Bulge_Desert_exr.zip](https://github.com/FlaxEngine/FlaxEngine/files/14986859/Ridge_Bulge_Desert_exr.zip)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/a4c0d12c-7d7a-4421-a2f7-3cdb1d38d299)

**Comment by mafiesto4** [comment] 2024-04-16 13:20
Added support for importing `exr` images in 1a87e5a2cada45f73faf626da35420bc9fe004d1.

Closing as it looks like content-issue to me.

**Closed by mafiesto4** 2024-04-16 13:20 UTC
Labels: bug, terrain
