### ISSUE TITLE
Changing scene errors editor window

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#486] opened 2021-04-26 23:57 UTC
When you change a scene the selected object in editor becomes null which in turns spams your console with errors. Prob. not a thing you want.

**Comment by stefnotch** [comment] 2021-04-27 05:52
I can't reproduce this, what steps are needed to reproduce?

Basically, I opened a scene, selected an object and then opened a different scene. That works.

**Comment by honzapatCZ** [comment] 2021-04-27 16:30
> I can't reproduce this, what steps are needed to reproduce?
> 
> Basically, I opened a scene, selected an object and then opened a different scene. That works.

Do it ingame, like select something, than from game unload a scene and load another ano and you will get editor errors

**Comment by mafiesto4** [comment] 2021-05-17 08:25
Fixed by 4392e07cd64ed62e56edaf0b58f2ba657cba667b.

**Closed by mafiesto4** 2021-05-17 08:25 UTC
Labels: bug, confirmed, editor
