### ISSUE TITLE
[Suggestion] Decal Layers or Decal Object Mask

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2603] opened 2024-05-16 19:32 UTC
It'd be nice to have a way to include or exclude a set objects or singluar objects, to control where decals can draw on. Currently they draw on everything withing the decal box, meaning blood can appear and disappear on a characters shoe as you walk through a decal

**Comment by Menotdan** [comment] 2024-05-16 19:33
There is an option on material slots in models to disable decals drawing on them but a more advanced system could be useful.

**Comment by Myterian** [comment] 2024-05-16 19:45
I mean, that is not an ideal solution. But it helps in this case. At least until the character is supposed to get decals, too

**Comment by Tryibion** [comment] 2024-05-17 03:53
Duplicate of <https://github.com/FlaxEngine/FlaxEngine/issues/967>

**Closed** 2024-05-17 13:20 UTC
Labels: duplicate, graphics, suggestion
