### ISSUE TITLE
Saving Game Settings with Copyright Symbol breaks file

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1994] opened 2023-11-26 02:02 UTC
**Issue description:**
After saving the Game Settings Asset you cannot reopen it. Reloading the project will display a white file in the content view. I found that the reason is the json asset is missing a second closing bracket after being saved.

**Steps to reproduce:**
1. Edit Game Settings
2. Save and try reopen
3. Look at file with code editor, see missing bracket

**Minimal reproduction project:**
Blank

**Flax version:**
1.7.6406.1

**Comment by Menotdan** [comment] 2023-11-26 03:31
I can't reproduce this, what platform are you on?

**Comment by Myterian** [comment] 2023-11-26 14:55
Windows and Engine is installed from the launcher. Just checked again, still there

**Comment by Menotdan** [comment] 2023-11-27 04:41
Ok after watching the video I identified the more specific issue. It will only crash when you have character that isn't what VSCode calls a "basic ASCII character". This may be contributing to the issue. If I add multiple of these non-basic ASCII characters, it removes more of the file. A better step to reproduce is simply:
1. Open a blank project
2. Open the GameSettings
3. Paste the following character into the "Copyright Notice field": `©` (and also maybe add some extra text, I didn't test extensively)
4. Save the GameSettings
5. Close GameSettings
6. Try to reopen and it's broken.

I think a better title for the issue would be "Saving GameSettings With A Copyright Symbol Breaks File", or something like that.

**Comment by Myterian** [comment] 2023-11-27 11:50
You're right, it's the copyright symbol

**Comment by mafiesto4** [comment] 2024-02-21 22:26
Fixed in f20805e56701ab4ec118188891e348efe124694c.

**Closed by mafiesto4** 2024-02-21 22:26 UTC
Labels: bug, editor, content
