### ISSUE TITLE
[Feature Request] Painting physical materials on terrain.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2159] opened 2024-01-05 07:22 UTC
It would be useful to be able to assign physical materials to terrain layers for painting, in order to provide a consistent interface for reading environment type from the terrain at any given point (including if you change up the material palette you use for part of the terrain).

Currently, you can assign physical materials to smaller objects, such as a floor or a carpet to provide an interface to read the surface type and operate on it, perhaps playing wood footstep sounds for a "Wood" physical material and playing carpet footstep sounds for the "Carpet" physical material. However, you can't do this on terrain, so you are stuck dealing with an inconsistent interface for reading surface types and having to create a map between terrain layer and surface type to operate based on the surface type.

**Comment by mafiesto4** [comment] 2024-02-14 11:52
Duplicate of #1112

**Closed by mafiesto4** 2024-02-14 11:52 UTC
Labels: suggestion, physics, terrain

**Comment by mafiesto4** [comment] 2024-02-16 22:17
Added in https://github.com/FlaxEngine/FlaxEngine/commit/42b4443e14030baca6658eb525b1e064041dec4a.

Tutorial: https://github.com/FlaxEngine/FlaxDocs/blob/9f61338e5abc583163f6cf37f8381108333d4de3/manual/physics/tutorials/footsteps.md
