### ISSUE TITLE
Gltf models import scale doesnt take effect

### ISSUE THREAD

**Issue by LordCocoNut** [FlaxEngine/FlaxEngine#1693] opened 2023-10-12 20:24 UTC
## What is the problem
- Importing gltf models, make them be imported really tiny. I tried to edit blender export settings (as the unit system in blender is a bit different and UE had some problems when importing fbx) but with no luck. The model is always tiny.
- importing / reimporting with different scale doesnt take any effect

## How to reproduce
Try to import gltf2 file  with a 100 scale to match blender units resize.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/46499313/25cfa87b-0e68-4811-9e78-31b275d3a0a0)

flax_multiple_context_menus

Setup > PopOs 22.04 LTS
Amd RX 6800XT
Flax 1.6 Build v. 6344

**Comment by mafiesto4** [comment] 2023-10-13 14:06
Duplicate of #1445, fixed in 8007417fe53ad1dd2767abfe7a9312bbd5ec3cf7

**Closed by mafiesto4** 2023-10-13 14:06 UTC
Labels: bug, content
