### ISSUE TITLE
Assertion failed when prefab is spawned immediately after new loading a new scene

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#560] opened 2021-06-24 06:20 UTC
**Issue description:**
The error is thrown when prefab (with Rigidbody as root) is spawned immediately after loading a new scene
Its caused by bounding sphere and bounding box values being `-NaN` for some reason.

**Steps to reproduce:**
Do script like this:
```cs
Level.LoadScene(id));
Scene scene = Level.FindScene(id);
PrefabManager.SpawnPrefab(prefab, scene);
```

**Stack trace:**
```
Expression: !box.Minimum.IsNanOrInfinity() && !box.Maximum.IsNanOrInfinity()
[ 00:05:37.435 ]: [Error] 
[ 00:05:37.505 ]: [Error] Stack trace:
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!Log::Logger::Write() in D:\Repozytoria\FlaxEngine\Source\Engine\Core\Log.cpp:line 252
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!PlatformBase::Assert() in D:\Repozytoria\FlaxEngine\Source\Engine\Platform\Base\PlatformBase.cpp:line 424
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!BoundingSphere::FromBox() in D:\Repozytoria\FlaxEngine\Source\Engine\Core\Math\BoundingSphere.cpp:line 124
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!RigidBody::OnTransformChanged() in D:\Repozytoria\FlaxEngine\Source\Engine\Physics\Actors\RigidBody.cpp:line 608
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!PrefabManager::SpawnPrefab() in D:\Repozytoria\FlaxEngine\Source\Engine\Level\Prefabs\PrefabManager.cpp:line 93
[ 00:05:37.505 ]: [Error]     at FlaxEditor.exe!PrefabManagerInternal::SpawnPrefab4() in D:\Repozytoria\FlaxEngine\Cache\Intermediate\FlaxEditor\Windows\x64\Development\Level\Level.Bindings.Gen.cpp:line 6371
```
**Flax version:**
Master branch

**Comment by mafiesto4** [comment] 2021-06-30 10:21
I was unable to reproduce it. Could you post a simple reproduction project or that prefab with this script? It might be that PhysX returns NaNs or maybe that prefab had sth wrong.

**Comment by Menotdan** [comment] 2023-12-08 01:24
@mafiesto4 Is there a reason this is open still?
@Crawcik Could you confirm whether or not this bug still occurs on the latest Flax version? If you still have the reproduction case around of course..

**Comment by mafiesto4** [comment] 2023-12-08 09:31
We did many fixes last year for actors to properly initialize transformation data in case someone spawns them from code and adds to the level after some operations so I guess it's fixed now.

**Closed by mafiesto4** 2023-12-08 09:31 UTC
Labels: bug, core, prefabs
