### ISSUE TITLE
Editor crashes with assertion on Assets.ContainsKey(id) in Content.cpp

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1930] opened 2023-11-13 18:49 UTC
**Issue description:**
Repeatedly the editor crashes especially when leaving the game mode with an assertion in Content.cpp.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13339799/Log.txt)

It happens frequently but not every time.

**Flax version:**
1.7 (master branch)

**Comment by mafiesto4** [comment] 2023-11-14 08:49
Would you mind testing with the latest master?

**Comment by nothingTVatYT** [comment] 2023-11-14 19:09
It took a while but it happened again.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13354993/Log.txt)

**Comment by nothingTVatYT** [comment] 2023-11-18 02:00
In git master as of Nov 17th it occurred again.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13398669/Log.txt)

**Comment by mafiesto4** [comment] 2023-11-23 16:41
I just got sth similar when loading level that uses Prefabs - probably caused by recent changes to Scenes Loading since now prefabs are loaded on Job System which boosts perf but caused this threading issue.

**Comment by nothingTVatYT** [comment] 2023-11-23 18:56
It's hard to reproduce - at least for me. It didn't happen yesterday at all and I had that in the past too, like the bug is pausing for a day or two and then comes back to hit me several times in a row. I'd love to provide more details but that beast seems to be very random.

**Comment by mafiesto4** [comment] 2023-11-24 09:29
Fixed in 359d4ba8efe5efd0e1cb7fd17f61094df988c63c. Now content loading properly handles thread-safety - especially in cases when for example 16 threads of Job System decide to load the same Prefab asset at once when loading scene in async. This will handle loading on the first thread, the rest of them will wait for the result without entering this assertion.

**Closed by mafiesto4** 2023-11-24 09:29 UTC
Labels: confirmed, crash, core
