### ISSUE TITLE
Navmesh seems to occasionally break when I open my Project

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#369] opened 2021-03-19 11:37 UTC
**Issue description:**
Occasionally when I open my project, I get these errors:
![image](https://user-images.githubusercontent.com/35228400/111774306-62c64400-8903-11eb-94dd-0b0c8c60ab1d.png)
I can't fix the issue by just rebuilding the Navmesh.
Instead I have to slightly move the mesh and then I can recalculate the NavMesh.

Here is the logs:
[Log_2021_03_20_22_33_20.txt](https://github.com/FlaxEngine/FlaxEngine/files/6170792/Log_2021_03_20_22_33_20.txt)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment] 2021-03-25 20:45
Finally, I was able to reproduce it. The problem was a bug in navmesh tiles data resizing logic. Fixed in: 2b741cae580b7f648a5e9abe2b20c55d173d460b.

**Closed by mafiesto4** 2021-03-25 20:45 UTC
Labels: bug
