### ISSUE TITLE
Copy pasting UIControls is not very practical nor actually working

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#487] opened 2021-04-26 23:58 UTC
Duplicating an UIControl wont place it properly if used inside something like VerticalLayout. Prob something with refreshing and child order

**Comment by stefnotch** [comment] 2021-04-27 05:55
I honestly cannot reproduce this, I'm probably missing something obvious? Screenshot/steps to reproduce please.

I basically tried a button in a `FlaxEngine.GUI.VerticalPanel`. Duplicating it with `Ctrl`+`D` seems to work as expected.

**Comment by honzapatCZ** [comment] 2021-04-27 06:52
> I honestly cannot reproduce this, I'm probably missing something obvious? Screenshot/steps to reproduce please.
> 
> I basically tried a button in a `FlaxEngine.GUI.VerticalPanel`. Duplicating it with `Ctrl`+`D` seems to work as expected.

Oh, Iam using Ctrl C + Ctrl V

**Comment by mafiesto4** [comment] 2021-04-29 07:43
Could you give an example of this issue? Copy pasting of UI works fine for me, maybe I'm doing sth different way.

**Comment by honzapatCZ** [comment] 2021-04-29 08:20
> Could you give an example of this issue? Copy pasting of UI works fine for me, maybe I'm doing sth different way.

Do ctrl c and then ctrl v into the same parent. This will paste the ui, but the actual order used by the ui system will be wrong, you then have to manualy drag it to change the order and it will synchronize

**Comment by mafiesto4** [comment] 2021-04-29 09:08
Ctrl+V pastes the control inside the currently selected by design. Ctrl+D is for duplicating stuff.

**Comment by honzapatCZ** [comment] 2021-04-29 09:11
> Ctrl+V pastes the control inside the currently selected by design. Ctrl+D is for duplicating stuff.

Ye, Iam aware of that, I Ctrl+C the child, select parent, do Ctrl+V which will paste it correctly, but the order is wrong.

**Comment by mafiesto4** [comment] 2021-04-29 09:30
Okay now I see it. For the next time: please provide step-by-step guidance how to reproduce issue (more professional approach).

**Comment by mafiesto4** [comment] 2021-04-29 14:22
Fixed in https://github.com/FlaxEngine/FlaxEngine/commit/c2afe0b6b2806b68cd9ff70f2af7e0c305fe72e0 and https://github.com/FlaxEngine/FlaxEngine/commit/d2ac0429d3cdc722b4e0195a226fcddab145be7f.

**Closed by mafiesto4** 2021-04-29 14:22 UTC
Labels: bug, confirmed, editor, ui
