### ISSUE TITLE
Skinned or animated FBX not imported correctly  

### ISSUE THREAD

**Issue by TheOmnisimush** [FlaxEngine/FlaxEngine#1525] opened 2023-09-26 04:28 UTC
**Issue description:**
Some animated FBXs are not correctly imported as SkinnedModel in Flax.
They are succesfully imported as .flax file, but will have some problems when run as SkinnedModel with animation.

For examples, these FBX models from Sketchfab:
https://sketchfab.com/3d-models/etrian-odyssey-3-monk-815389a67c1e49808400b0b86a7ea17f
https://sketchfab.com/3d-models/midas-fortnite-100-tier-s12-bp-skin-23ca8a5c57674b7d984e802e2ed4a436

These models are imported correctly both in Unity and Unreal, so I think there are some bugs inside Flax's FBX parser/importer code.

**Expected Result:**
The FBX is imported correctly and animates the same as the models shown in Sketchfab.
Since Flax recommends using FBX as their 3D Model base, this is crucial.
I also post the same problem in Flax forum :
https://forum.flaxengine.com/t/fbx-not-imported-correctly/1277

**Steps to reproduce:**
- Download FBX from the Sketchfab links above
- Import to Flax as SkinnedModel
- Import the same model (because the animation is inside the same FBX) as Animation
- Create new AnimationGraph and attach the animation above
- Attach AnimationGraph to SkinnedModel
- Hit Play

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment] 2023-10-03 18:45
Honestly, that bug is pretty hard to fix. I tried, tweaking different options and matrices for bones but it looks like OpenFBX lib we use for fbx files importing cannot import those meshes properly. Maybe we should migrate to Autodesk FBX SDK (at the cost of worse performance and installation issues due to licensing).

**Comment by mafiesto4** [comment] 2023-10-03 18:51
Maybe because it was exported by Blender :)

**Comment by mafiesto4** [comment] 2023-10-03 19:03
I think the problem is that we set the Bind Pose of the imported Skinned Model as T-Pose of the meshes instead of the first frame from the animation included in that file (which is also a skeleton pose). So that's why the animation doesn't work as intended.

**Comment by TheOmnisimush** [comment] 2023-10-04 06:26
@mafiesto4 
Thanks for replying.

> Maybe we should migrate to Autodesk FBX SDK (at the cost of worse performance and installation issues due to licensing).
yes, that's what I thought too. Because FBX format has changed quite alot with each version, it will be hard to maintain all of the variations.

> I think the problem is that we set the Bind Pose of the imported Skinned Model as T-Pose of the meshes instead of the first frame from the animation included in that file (which is also a skeleton pose).
Maybe you can add a "manual option" in Model importer window, so we can choose which initial pose we want to import the model with.

For current Flax version, the only workaround is to have an FBX which has the same initial Mesh pose and same initial Bone Pose. This is fine especially with developer who is capable to make their own custom models, however since not all users are able and willing to create their own 3D Model, most will probably just buy or download free models they can find in sites like Sketchfab

**Comment by mafiesto4** [comment] 2023-10-04 10:47
Okay the first problem was with Flax calculating own Offset Matrix (aka Bind Pose matrix for bone). Fixed in 68a713fb951aa121a01bd6966407e762cecbdf78.

The second problem was space conversion - Blender exporter uses a different Up axis value (`1`) while Autodesk SDK and models exported with Autodesk use value `2` so I fixed that in b3b6251c107ee210ef7cfa7d8a44d3298f02acca and 52b9a995add6ea7b475c1247b4469b4a97978ec5.

The last problem was the incorrect skinning of meshes that don't have `skin` exported (eg. that girl's hair) so the improper was using `root` node instead, now it properly adds missing bone that links to the proper node and makes the skeleton look good. Fixed here 9fa709aa79785fff61704e77751d81a87617f389.

Now, I have the following result which looks pretty good:

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/1e604305-dc86-4401-b11f-db508c97047d

(it took a whole day  to fix but was totally worth it!)

**Comment by TheOmnisimush** [comment] 2023-10-06 04:34
Hi, I have confirmed that these 2 models are imported correctly in the latest master branch.
Thanks for your work.

However, I also tried to test with other models and there are still some models not being imported correctly
like the one I post in the forum
https://forum.flaxengine.com/t/fbx-not-imported-correctly/1277/11

Can you please take a look at this? thank you

**Comment by mafiesto4** [comment] 2023-10-06 08:15
Works fine to me:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/b9a70abc-fe7f-44fb-b7bb-21ffe686be00)

**Comment by TheOmnisimush** [comment] 2023-10-27 02:32
@mafiesto4 
I am terribly sorry to revisit this issue, 
the above link is the FBX that I got fixed by  :
- first import it to Unreal
(Unreal somehow import this correctly) 
- then in Unreal, re-export it as a new “Fixed” FBX
- the newly fixed FBX is imported correctly in Flax

This is the original raw FBX that is not imported correctly in Flax
https://drive.google.com/file/d/1J8zwlxC6mnwbN7_bqoMivkPQ5kyuZ5Va/view?usp=drive_link

**Comment by OnyeNacho** [comment] 2023-11-05 11:30
I having a similar problem with my character imports as well. I made them entirely in Autodesk 3DS Max.

![01](https://github.com/FlaxEngine/FlaxEngine/assets/2350777/6ffbbf2a-6e2a-4dbc-ac1e-ed82e87779d6)
![02](https://github.com/FlaxEngine/FlaxEngine/assets/2350777/a48e939c-2f2b-44c6-9e19-9d05ef88c6a0)
![03](https://github.com/FlaxEngine/FlaxEngine/assets/2350777/2a9261fd-a8f2-45ca-bb3d-dc5c90070d4e)

**Comment by OnyeNacho** [comment] 2023-11-06 13:02
HALLELUJAH! The UE4 workaround worked! Same even applies with the animations!
![01](https://github.com/FlaxEngine/FlaxEngine/assets/2350777/821169e3-46bf-4cca-a686-33172463f8ac)

**Closed** 2023-11-12 12:21 UTC
Labels: bug, confirmed, animations, content

**Comment by Menotdan** [comment] 2023-11-12 15:20
Why was this closed if a workaround is still required to work properly?

**Comment by mafiesto4** [comment] 2023-11-12 17:27
The source models attached to this issue were fixed and are working fine. If there are other ones to solve feel free to attach them here and reopen issue or create a new issue with specific assets that have problems with importing to Flax.
