### ISSUE TITLE
Custom Post Process Materials will stack and don't blend

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1991] opened 2023-11-25 23:07 UTC
**Issue description:**
When you assign a custom post process material to a global and a bounded post processing volumes and walk into the bounded volume, the materials will stack on top of each other and amplify the effect. 

The effect of the global volume won't change and act as a base effect and the effect from the bounded volume will just be added on top. It almost looks like the effect is being done twice.

Also, there is no blending occuring. Custom effect will just pop in.

**Steps to reproduce:**
1. Create custom post process material and create two instances with different intensities / values.
2. Create two post processing volumes, one global and one bounded, and assign a material instance to each respectively
3. Play and walk into the volume, let the effects will pop in and also look stronger

**Minimal reproduction project:**
Blank

**Flax version:**
1.7.6406.1

**Comment by Menotdan** [comment] 2023-11-26 00:14
> It almost looks like the effect is being done twice.
That's because it is lol
Why is this not intended behavior? If you want to stack post FX, how are you meant to do that if it just ignores the other layers?

**Comment by Myterian** [comment] 2023-11-26 01:03
Intended behaviour would be to blend the values, if an effect is present in both volumes like the build-in effects do. Stacking effects with different volumes means that an effect is only present in one of the volumes, else there is no need to stack

**Comment by mafiesto4** [comment] 2023-12-27 20:23
Fixed in b275ffc146923eb11de0ea7611b945d8c36072e1

**Closed by mafiesto4** 2023-12-27 20:23 UTC
Labels: bug, graphics
