### ISSUE TITLE
Color deviation with low poly meshes

### ISSUE THREAD

**Issue by Amphipiron** [FlaxEngine/FlaxEngine#628] opened 2021-09-23 04:55 UTC
Regarding to this forum topic: https://forum.flaxengine.com/t/imported-mesh-non-skeletal-has-color-deviation/469/3

**Issue description:**

There is color-deviation at low poly meshes (using with color palettes). The cube should have been red but was orange.

**Steps to reproduce:**

It was just a basic project, importing a simple colored cube as .fbx

**Minimal reproduction project:**

[testCube.zip](https://github.com/FlaxEngine/FlaxEngine/files/7215057/testCube.zip)
Thats the fbx-file I was using.

**Flax version:**

Flax-Version 1.2

**Comment by mafiesto4** [comment] 2021-09-23 10:41
For me it looks like an issue with normals:
![image](https://user-images.githubusercontent.com/3464853/134493203-4a92000a-f1bf-4fe6-b3df-6700a7ac8e52.png)

Caused by using color texture as normalmap in default auto-generated material (fixed in: 257f57f9267d4e68b6e57492cdab370de47f550a). Does removing it helps with the problem?

![image](https://user-images.githubusercontent.com/3464853/134493292-985a4497-a901-46a2-8a72-69a3b6e76105.png)

**Comment by Amphipiron** [comment] 2021-09-23 13:09
I had to remove the texture and the emission link, but now it seems to work.

![Flax_cube_new](https://user-images.githubusercontent.com/28346457/134512637-1c0a08e5-0a73-4cc5-b1bc-88ec37f2b4f0.jpg)

**Comment by mafiesto4** [comment] 2021-09-24 18:17
Yeah, the fbx models importer after the fix generates proper materials now. Thanks!

**Closed by mafiesto4** 2021-09-24 18:17 UTC
Labels: graphics
