### ISSUE TITLE
[Info] Vulkan Validation Errors reported in Debug build

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1998] opened 2023-11-26 23:49 UTC
I noticed a big performance drop in the current debug build and in the logs a lot of "Validation Error" are reported.
This issue may be linked to the sporadic crashes on Vulkan-based systems but I will drop the log files here as I'm not sure.

I build both the Debug and Development versions of Flax in the current git master and opened the same project. The project consists of the default (sky, floor, etc.) plus an animated character and a custom UIControl.
Even on loading there is a noticeable delay on this small project and the editor view is at around 50-55 FPS with the debug build. The development build is faster in loading and more responsive and has no problem keeping the typical 60-61 FPS.

Anyway the performance drop is most probably just a symptom of an underlying issue reported in the log files.
[Log_2023_11_27_00_35_53.txt](https://github.com/FlaxEngine/FlaxEngine/files/13468454/Log_2023_11_27_00_35_53.txt)
[Log_2023_11_27_00_36_30.txt](https://github.com/FlaxEngine/FlaxEngine/files/13468455/Log_2023_11_27_00_36_30.txt)

(By the way: Something is wrong with the timestamps around midnight.)

**Flax version:**
1.7.6406.1

**Comment by mafiesto4** [comment] 2024-02-27 16:33
I was unable to reproduce it on Windows with `GeForce RTX 2080 Ti` and VulkanSDK `1.3.261.1` (branch `1.8`). Maybe Linux specific.

**Comment by mafiesto4** [comment] 2024-02-27 16:34
Duplicate of #1825

**Closed by mafiesto4** 2024-02-27 16:34 UTC
Labels: bug, graphics
