### ISSUE TITLE
Spline doesn't work in prefabs

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#2474] opened 2024-04-23 07:16 UTC
- Empty project in 1.8
- Create a prefab
- Add a spline to it
- This happens:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/3651cd1f-da2a-44c7-8456-ff9206607568)

```
[Warning] Exception has been thrown during Window.OnMouseUp. Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Stack strace:
   at FlaxEditor.CustomEditors.Dedicated.SplineEditor.Refresh() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\SplineEditor.cs:line 346
```

Notice that the UI is broken on the right side of the prefab window. It fixes when the window is resized.  Saving doesn't work, and moving the spline points around becomes buggy.

**Comment by GoaLitiuM** [comment] 2024-04-23 17:31
Duplicate of #2383, also fixed in master branch

**Closed by GoaLitiuM** 2024-04-23 17:31 UTC

**Comment by lifeformed** [comment] 2024-04-24 04:24
Oh! Sorry.  I was actually on master but I was a few commits behind.
