### ISSUE TITLE
[Inputs Request] Add Gamepad buttons to Input AxisMapping

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2514] opened 2024-04-28 12:25 UTC
**Issue description:**
I need to use common buttons like, north, south, east and west as axis but the current input implementation allow to use only triggers and joysticks.

Any plans to add support for any button type to the input axis?

**Flax version:**
1.8.1

**Comment by mafiesto4** [comment] 2024-04-29 16:29
Duplicate of #2430. I added to 1.9 milestone as it's requested feature.

**Closed by mafiesto4** 2024-04-29 16:29 UTC
Labels: duplicate, input, suggestion
