### ISSUE TITLE
BoundingSphere::FromBox crashes

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#2118] opened 2023-12-21 23:28 UTC
i managed to trigger it in more than 10 ways this function needs a fix
or whatever function is creating the nan value
this is one of the ways
by setting a Y value in blender 2D to -1
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/935d6d99-c938-4a72-82e5-ff3e3561d5fc)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/b4f13b11-2eb6-47e9-9be2-6badb5860432)

**Hacky Fix in:**
- https://github.com/FlaxEngine/FlaxEngine/pull/1628

**Flax version:**

https://github.com/FlaxEngine/FlaxEngine/commit/4e34524a08ea0d8593e8578068bdc1d0fbdfee2e

**Comment by Menotdan** [comment] 2024-01-01 06:56
I think fixing the functions passing bad values is a better idea overall since returning without actually populating the output sphere could cause some problematic results..
On the other hand, this function is exposed to the API, so if someone passes in a bad value it shouldn't crash. I think fixing both would be the ideal solution. `SOFT_ASSERT` is a reasonable solution to the second problem, but the first issue should also be solved.

**Comment by mafiesto4** [comment] 2024-01-05 12:09
Fixed crashes due to invalid animated model nodes data in d9ca3e5b57df31bbb0116369f6de166c5df1a8c6 (for future to be stable).

It was caused by incorrect sampling of Multi Blend 2D that had wrong triangle, fixed in 60fd4702a626241ef80293250f7be083ee9decb5

**Closed by mafiesto4** 2024-01-05 12:09 UTC
Labels: confirmed, crash, animations
