### ISSUE TITLE
Multi Blend 2D Playing Incorrect Animation

### ISSUE THREAD

**Issue by Kh4iri** [FlaxEngine/FlaxEngine#2553] opened 2024-05-04 23:20 UTC
**Issue description:**
Occasionally, the Multi Blend 2D plays an incorrect animation. This problem typically arises when both the X and Y values are non-zero. For instance, in the video provided, the Y value is 100 and the X value is -100, yet it triggers the right strafe animation instead of the left strafe animation.

https://github.com/FlaxEngine/FlaxEngine/assets/99790424/7b069195-ffbf-4725-9b64-42a4bde6f4b8

**Steps to reproduce:**
1. Open the project I provided
2. Open Contents/Animations/Robot Anim Graph

**Minimal reproduction project:**
[TestProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/15211216/TestProject.zip)

**Flax version:**
1.8.1

**Comment by Muzz** [comment] 2024-05-05 08:14
The issue is that the engine uses triangulated blending, so imagine triangles drawn between the dots. The interpolation of those points outside of the triangles isn't very intuitive which should be fixed imo. But if you keep the values within the triangles, it works correctly.

**Comment by Kh4iri** [comment] 2024-05-05 13:20
Ah thanks for the explanation! I got it working using your solution. I also agree that this issue should be fixed or at least mentioned somewhere.

https://github.com/FlaxEngine/FlaxEngine/assets/99790424/f3701eb8-19e7-4b27-8372-0835ee272e04

**Comment by mafiesto4** [comment] 2024-08-28 14:50
Fixed in 046865ba00ef8edb1dad844333cb73ed652906d7.

**Closed by mafiesto4** 2024-08-28 14:50 UTC
Labels: bug, animations
