### ISSUE TITLE
Random silent crash in Behavior Trees

### ISSUE THREAD

**Issue by happy-bracket** [FlaxEngine/FlaxEngine#1863] opened 2023-11-02 14:31 UTC
**Issue description:**
Some well-defined (afaik, according to documentation) trees sometimes cause the game and editor to crash on start or on stop. No error/crash logs are produced when that happens. However, if debugger is attached, it will catch an exception, at least in repro project:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/33666545/8cb39ad1-4d3a-407e-9e1d-6b8fdfa3b601)

**Steps to reproduce:**
Open project, then repeatedly start (F5) and stop (Esc) the game in editor until it crashes.
Files of interest are `Source/Game/BrokenNode.cs` and `Content/BrokenBT`

**Minimal reproduction project:**
[Playground.zip](https://github.com/FlaxEngine/FlaxEngine/files/13240847/Playground.zip)

**Flax version:**
1.7.6404

**Comment by mafiesto4** [comment] 2023-11-04 18:31
The problem was caused by a bug in `BitArray::SetAll()` method that was not working properly. Fixed in 3bf7b57dbd6280f0a8d0ff6989c9e1b3ed3d548f. I added automated test to ensure we don't have regression on this.

Also, ensure to properly return size of the C# BT node state as in example code:
```cs
/// <inheritdoc />
public override int GetStateSize()
{
    // Return size of the per-instance node memory to allocate
    return GetStateSize<State>();
}
```

**Closed by mafiesto4** 2023-11-04 18:31 UTC
Labels: confirmed, crash, ai
